import './globals.css'
import { Playfair_Display } from 'next/font/google'
import Link from 'next/link'

const playfair = Playfair_Display({ subsets: ['latin'] })

export const metadata = {
  title: 'NairobiCakes - Luxury Cake Delivery',
  description: 'Order exquisite cakes from local bakeries in Nairobi',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${playfair.className} bg-cream text-purple-900`}>
        <header className="bg-purple-900 text-gold p-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-3xl font-bold">NairobiCakes</h1>
            <nav>
              <ul className="flex space-x-4">
                <li><Link href="/" className="hover:text-cream transition-colors">Home</Link></li>
                <li><Link href="/customer/catalog" className="hover:text-cream transition-colors">Catalog</Link></li>
                <li><Link href="/customer/login" className="hover:text-cream transition-colors">Customer Login</Link></li>
                <li><Link href="/baker/login" className="hover:text-cream transition-colors">Baker Login</Link></li>
              </ul>
            </nav>
          </div>
        </header>
        <main className="container mx-auto p-4">
          {children}
        </main>
        <footer className="bg-purple-900 text-gold p-4 mt-8">
          <div className="container mx-auto text-center">
            <p>&copy; 2023 NairobiCakes - Luxury Cake Delivery</p>
          </div>
        </footer>
      </body>
    </html>
  )
}
